config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pictures do
    member do
      put 'like', to: 'pictures#upvote'
    end
  end
  root 'pictures#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  acts_as_votable
  belongs_to :user

  has_attached_file :image, styles: { medium: '300x300>', large: '500x500>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :user_name) }

    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :user_name) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :user_name) }
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :find_picture, only: %i[show edit destroy update upvote]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @pictures = Picture.all.order('created_at desc')
  end

  def show; end

  def new
    @picture = current_user.pictures.build
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    if @picture.save
      redirect_to @picture, notice: "Post '#{@picture.title}' was created successfully!"
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @picture.update(picture_params)
      redirect_to @picture, notice: "Post '#{@picture.title}' was updated successfully!"
    else
      render 'edit'
    end
  end

  def upvote
    @picture.upvote_by current_user
    redirect_to @picture
  end

  def destroy
    @picture.destroy
    redirect_to root_path, notice: 'Post was deleted successfully!'
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :description, :image)
  end

  def find_picture
    @picture = Picture.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title InstaPics
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags


%body

  = render 'shared/nav'

  .container
    = yield

    = render 'shared/alerts'

app/views/pictures/_form.html.haml
= simple_form_for @picture, html: { multipart: true} do |f|
  - if @picture.errors.any?
    #errors
    - @picture.errors.full_messages do |error|
      = js add_gritter(error, title: 'InstaPics Notification', sticky: false)

  .form-group
    = f.input :image, input_html: { class: 'form-control' }
  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, class: 'btn btn-info'

app/views/pictures/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Picture
      .panel-body
        .current_image
          %strong.center Right Now
          = image_tag @picture.image.url(:medium)
        = render 'form'

app/views/pictures/index.html.haml
.col-md-6.col-md-offset-3
  #pictures.transitions-enabled
    - @pictures.each do |picture|
      .box.panel.panel-default
        = link_to (image_tag picture.image.url), picture
        %h2= link_to picture.title, picture

app/views/pictures/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Post Picture
      .panel-body
        = render 'form'

app/views/pictures/show.html.haml
#pic_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel.heading.pic_image
        = image_tag @picture.image.url(:large)
      .panel-body
        %h1= @picture.title
        %p= @picture.description
      .panel-footer
        .row
          .col-md-6
            %p.user
              Posted by
              = @picture.user.user_name

          .col-md-6
            .btn-group.pull-right
              = link_to like_picture_path(@picture), method: :put, class: 'btn btn-default' do
                %span.glyphicon.glyphicon-heart
                = @picture.get_upvotes.size

              - if user_signed_in?
                = link_to 'Edit Picture', edit_picture_path, class: 'btn btn-info'
                = link_to 'Delete Picture',  picture_path, method: :delete, data: { confirm: 'Do you really want to delete this picture?' }, class: 'btn btn-danger'

app/views/shared/_alerts.html.haml
- if flash[:alert]
  = js add_gritter(flash[:alert], title: 'InstaPics Alert', sticky: false)
- elsif flash[:error]
  = js add_gritter(flash[:error], title: 'InstaPics Error', sticky: false)
- else
  = js add_gritter(flash[:notice], title: 'InstaPics Notification', sticky: false)

app/views/shared/_nav.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-brand= link_to "InstaPics", root_path

    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-left
        %li= link_to "Post Pic", new_picture_path
        %li= link_to "Settings", edit_user_registration_path
        %li= link_to "Sign Out", destroy_user_session_path, method: :delete

    - else
      %ul.nav.navbar-nav.navbar-left
        %li= link_to "Sign Up", new_user_registration_path
        %li= link_to "Sign In", new_user_session_path